// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkMMJ7xBVxz_N0vsB2y-D6XBxnKsgXy1s',
    appId: '1:77396444992:web:74cbc9f1ef97e5956edca5',
    messagingSenderId: '77396444992',
    projectId: 'hello-push-messages',
    authDomain: 'hello-push-messages.firebaseapp.com',
    storageBucket: 'hello-push-messages.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8XkaWsaVIdmCGGRtAUADsSehzdKp2QaA',
    appId: '1:77396444992:android:21d5558b9c2d7e856edca5',
    messagingSenderId: '77396444992',
    projectId: 'hello-push-messages',
    storageBucket: 'hello-push-messages.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvczWUXYN1tos6GG8kbGlyaYoTsRBbLR8',
    appId: '1:77396444992:ios:3355300baec58b526edca5',
    messagingSenderId: '77396444992',
    projectId: 'hello-push-messages',
    storageBucket: 'hello-push-messages.firebasestorage.app',
    iosBundleId: 'com.example.hellopushmessages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvczWUXYN1tos6GG8kbGlyaYoTsRBbLR8',
    appId: '1:77396444992:ios:3355300baec58b526edca5',
    messagingSenderId: '77396444992',
    projectId: 'hello-push-messages',
    storageBucket: 'hello-push-messages.firebasestorage.app',
    iosBundleId: 'com.example.hellopushmessages',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkMMJ7xBVxz_N0vsB2y-D6XBxnKsgXy1s',
    appId: '1:77396444992:web:05b0dde052e0fe2d6edca5',
    messagingSenderId: '77396444992',
    projectId: 'hello-push-messages',
    authDomain: 'hello-push-messages.firebaseapp.com',
    storageBucket: 'hello-push-messages.firebasestorage.app',
  );
}
